"""Add last_billed_at column

Revision ID: c26984ba94bc
Revises: 
Create Date: 2025-10-26 23:30:56.154413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26984ba94bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('billing_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rate_per_gb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate_per_hour', sa.Float(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_billed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usage_bytes', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('usage_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mid_cycle_plan_change', sa.Boolean(), nullable=True))
        batch_op.drop_column('data_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_used', sa.BIGINT(), nullable=True))
        batch_op.drop_column('mid_cycle_plan_change')
        batch_op.drop_column('usage_hours')
        batch_op.drop_column('usage_bytes')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('last_billed_at')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('rate_per_hour')
        batch_op.drop_column('rate_per_gb')
        batch_op.drop_column('billing_type')
        batch_op.drop_column('connection_type')

    # ### end Alembic commands ###
